export const ADD_LOCATION_ROW = "ADD_LOCATION_ROW";
export const UPDATE_LOCATION_ROW = "UPDATE_LOCATION_ROW";
export const TOGGLE_SORT = "TOGGLE_SORT";
export const ADD_TABLE = "ADD_TABLE";
export const DELETE_TABLE = "DELETE_TABLE";
export const TOGGLE_LOCATION_STATUS = "TOGGLE_LOCATION_STATUS";
